/* SILKSHIFT. Original art and game. Native WebGL; no runtime dependencies. */
'use strict';
(() => {
const $=id=>document.getElementById(id), canvas=$('game');
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)), mix=(a,b,t)=>a+(b-a)*t;
let seed=17431; const random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};
const storage={get(k,f){try{return localStorage.getItem('silkshift.'+k)??f;}catch{return f;}},set(k,v){try{localStorage.setItem('silkshift.'+k,String(v));}catch{}}};
const C={road:[.10,.115,.18],walk:[.19,.19,.27],dark:[.09,.105,.18],pink:[1,.25,.43],cyan:[.35,.94,.87],gold:[1,.72,.32],white:[.94,.96,1],black:[.045,.06,.105]};
let gl,ext,program,batches,viewProjection,travel=0,worldTime=0;
const maxInstances=7000;
function fail(message){$('error-message').textContent=message;$('error').hidden=false;$('play').disabled=true;$('play-label').textContent='CITY UNAVAILABLE';}
$('reload').onclick=()=>location.reload();
function shader(type,source){const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s;}
function identity(){return new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]);}
function multiply(a,b){const o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)o[c*4+r]=a[r]*b[c*4]+a[4+r]*b[c*4+1]+a[8+r]*b[c*4+2]+a[12+r]*b[c*4+3];return o;}
function matrix(p,s,r=[0,0,0]){const [x,y,z]=r,cx=Math.cos(x),sx=Math.sin(x),cy=Math.cos(y),sy=Math.sin(y),cz=Math.cos(z),sz=Math.sin(z);return new Float32Array([cz*cy*s[0],sz*cy*s[0],-sy*s[0],0,(cz*sy*sx-sz*cx)*s[1],(sz*sy*sx+cz*cx)*s[1],cy*sx*s[1],0,(cz*sy*cx+sz*sx)*s[2],(sz*sy*cx-cz*sx)*s[2],cy*cx*s[2],0,p[0],p[1],p[2],1]);}
function norm(v){const l=Math.hypot(...v)||1;return v.map(n=>n/l);}function cross(a,b){return[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];}
function look(eye,target){const z=norm(eye.map((n,i)=>n-target[i])),x=norm(cross([0,1,0],z)),y=cross(z,x),dot=a=>-a.reduce((s,v,i)=>s+v*eye[i],0);return new Float32Array([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,dot(x),dot(y),dot(z),1]);}
function perspective(aspect){const f=1/Math.tan(54*Math.PI/360),n=.1,far=500;return new Float32Array([f/aspect,0,0,0,0,f,0,0,0,0,(far+n)/(n-far),-1,0,0,2*far*n/(n-far),0]);}
function cubeGeometry(){const v=[],faces=[[[1,0,0],[.5,-.5,-.5],[.5,.5,-.5],[.5,.5,.5],[.5,-.5,.5]],[[-1,0,0],[-.5,-.5,.5],[-.5,.5,.5],[-.5,.5,-.5],[-.5,-.5,-.5]],[[0,1,0],[-.5,.5,-.5],[-.5,.5,.5],[.5,.5,.5],[.5,.5,-.5]],[[0,-1,0],[-.5,-.5,.5],[-.5,-.5,-.5],[.5,-.5,-.5],[.5,-.5,.5]],[[0,0,1],[.5,-.5,.5],[.5,.5,.5],[-.5,.5,.5],[-.5,-.5,.5]],[[0,0,-1],[-.5,-.5,-.5],[-.5,.5,-.5],[.5,.5,-.5],[.5,-.5,-.5]]];for(const [n,...p]of faces)for(const i of[0,1,2,0,2,3])v.push(...p[i],...n);return v;}
function sphereGeometry(){const v=[],at=(i,j)=>{const t=i/8*Math.PI,p=j/12*Math.PI*2;return[Math.sin(t)*Math.cos(p),Math.cos(t),Math.sin(t)*Math.sin(p)];};for(let i=0;i<8;i++)for(let j=0;j<12;j++)for(const p of[at(i,j),at(i+1,j),at(i+1,j+1),at(i,j),at(i+1,j+1),at(i,j+1)])v.push(...p,...p);return v;}
function octaGeometry(){const v=[],a=[[1,0,0],[0,0,1],[-1,0,0],[0,0,-1]];for(let s of[-1,1])for(let i=0;i<4;i++){const p=[[0,s,0],a[i],a[(i+1)%4]],n=norm([a[i][0]+a[(i+1)%4][0],s,a[i][2]+a[(i+1)%4][2]]);for(const q of p)v.push(...q,...n);}return v;}
function makeBatch(vertices){const buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(vertices),gl.STATIC_DRAW);return{buffer,vertices:vertices.length/6,instance:gl.createBuffer(),data:new Float32Array(maxInstances*24),static:[],dynamic:[],count:0};}
function object(type,p,s,color,glow=0,scroll=0,r=[0,0,0],dynamic=false,parent=null){let m=matrix(p,s,r);if(parent)m=multiply(parent,m);const obj={m,color,glow,scroll};batches[type][dynamic?'dynamic':'static'].push(obj);return obj;}
function segment(a,b,width,color,glow=0,type='cube',parent=null){const y=norm(b.map((n,i)=>n-a[i])),x=norm(cross(Math.abs(y[1])>.99?[0,0,1]:[0,1,0],y)),z=cross(x,y),len=Math.hypot(...b.map((n,i)=>n-a[i]));const m=identity(),radius=type==='sphere'?.5:1;for(let i=0;i<3;i++){m[i]=x[i]*width;m[4+i]=y[i]*len*radius;m[8+i]=z[i]*width;m[12+i]=(a[i]+b[i])/2;}batches[type].dynamic.push({m:parent?multiply(parent,m):m,color,glow,scroll:0});}
function initGL(){gl=canvas.getContext('webgl',{alpha:true,antialias:true,powerPreference:'high-performance',preserveDrawingBuffer:false});if(!gl)throw Error('WebGL is unavailable. Enable hardware acceleration, or try another browser.');ext=gl.getExtension('ANGLE_instanced_arrays');if(!ext)throw Error('Your graphics device does not support instanced 3D rendering. Please try another browser.');program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,`precision highp float;attribute vec3 aPosition;attribute vec3 aNormal;attribute mat4 aModel;attribute vec4 aColor;attribute vec4 aMotion;uniform mat4 uVP;uniform float uTravel;varying vec3 vColor;varying float vFog;void main(){vec4 world=aModel*vec4(aPosition,1.0);if(aMotion.x>0.5){float z=mod(aModel[3].z+uTravel+245.0,280.0)-245.0;world.z+=z-aModel[3].z;}vec3 normal=normalize(mat3(aModel)*aNormal);float light=.44+max(dot(normal,normalize(vec3(-.4,.8,.5))),0.0)*.6;vColor=aColor.rgb*mix(light,1.22,aColor.a);vFog=smoothstep(55.0,265.0,-world.z);gl_Position=uVP*world;}`));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,`precision mediump float;varying vec3 vColor;varying float vFog;uniform vec3 uFog;void main(){gl_FragColor=vec4(mix(vColor,uFog,vFog*.94),1.0);}`));for(const[n,i]of[['aPosition',0],['aNormal',1],['aModel',2],['aColor',6],['aMotion',7]])gl.bindAttribLocation(program,i,n);gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program));gl.useProgram(program);gl.enable(gl.DEPTH_TEST);batches={cube:makeBatch(cubeGeometry()),sphere:makeBatch(sphereGeometry()),octa:makeBatch(octaGeometry())};}
function buildCity(){const add=(p,s,c,g=0,m=0,r)=>object('cube',p,s,c,g,m,r);add([0,-.42,-110],[12,.8,290],C.road);for(const side of[-1,1]){add([side*7,-.08,-110],[2,.4,290],C.walk);add([side*6.04,.05,-110],[.06,.06,290],C.pink,1);add([side*7.95,.15,-110],[.18,.6,290],C.dark);for(let z=-235;z<35;z+=14){add([side*7.65,2.6,z],[.09,5.2,.09],C.dark,0,1);add([side*7.24,5.17,z],[.9,.1,.12],C.cyan,1,1);add([side*6.7,.2,z],[.08,.06,4],C.cyan,.8,1);}for(let i=0;i<23;i++){const z=-240+i*12.2,w=4+random()*4,h=8+random()*35,d=6+random()*4,x=side*(10+w/2+random()*3),c=[.09+random()*.05,.11+random()*.055,.20+random()*.075];add([x,h/2,z],[w,h,d],c,0,1);add([x,h+.14,z],[w+.18,.3,d+.18],C.dark,0,1);if(i%3===0){add([x,h+.38,z],[w,.06,d],C.pink,1,1);add([x,h+1.3,z],[w*.25,2,d*.3],C.dark,0,1);add([x,h+3.4,z],[.07,3,.07],C.cyan,.7,1);}for(let row=1;row<h-1;row+=2.4){for(let col=-w/2+.65;col<w/2;col+=1.2)if(random()>.2){const color=random()>.65?[.87,.57,.45]:[.31,.63,.72];add([x+col,row,z+d/2+.025],[.48,.8,.025],color,.65,1);}for(let col=-d/2+.65;col<d/2;col+=1.8)if(random()>.3)add([x-side*(w/2+.025),row,z+col],[.025,.7,.65],i%2?C.cyan:[.6,.4,.62],.4,1);}if(i%4===1){add([x-side*(w/2+.16),h*.55,z],[.16,3.5,2],C.dark,0,1);for(let k=0;k<3;k++)add([x-side*(w/2+.26),h*.55-1+k,z],[.1,.35,1.3],C.pink,1,1);}}
for(let i=0;i<14;i++){let h=18+random()*45;add([side*(24+random()*50),h/2,-245+i*18],[6+random()*9,h,9],[.19,.2,.31],0,1);}}
for(let z=-235;z<35;z+=7)for(let x of[-1.7,1.7])add([x,.011,z],[.045,.02,2.8],[.43,.44,.54],.1,1);
object('sphere',[15,35,-255],[21,21,2],[1,.60,.49],1);for(let i=0;i<50;i++)object('sphere',[(random()-.5)*240,45+random()*75,-270],[.12,.12,.12],C.white,1);
}
function render(eye,target){const ratio=Math.min(devicePixelRatio||1,innerWidth<700?1.6:1.5),w=Math.floor(innerWidth*ratio),h=Math.floor(innerHeight*ratio);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}gl.viewport(0,0,w,h);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.useProgram(program);viewProjection=multiply(perspective(w/h),look(eye,target));gl.uniformMatrix4fv(gl.getUniformLocation(program,'uVP'),false,viewProjection);gl.uniform1f(gl.getUniformLocation(program,'uTravel'),travel);gl.uniform3f(gl.getUniformLocation(program,'uFog'),.57,.39,.49);for(const batch of Object.values(batches)){const all=batch.static.concat(batch.dynamic);let n=0;for(const obj of all){if(n>=maxInstances)break;const offset=n++*24;batch.data.set(obj.m,offset);batch.data.set([...obj.color,obj.glow],offset+16);batch.data.set([obj.scroll,0,0,0],offset+20);}batch.count=n;gl.bindBuffer(gl.ARRAY_BUFFER,batch.buffer);for(let i=0;i<2;i++){gl.enableVertexAttribArray(i);gl.vertexAttribPointer(i,3,gl.FLOAT,false,24,i*12);ext.vertexAttribDivisorANGLE(i,0);}gl.bindBuffer(gl.ARRAY_BUFFER,batch.instance);gl.bufferData(gl.ARRAY_BUFFER,batch.data.subarray(0,n*24),gl.DYNAMIC_DRAW);for(let i=2;i<8;i++){gl.enableVertexAttribArray(i);gl.vertexAttribPointer(i,4,gl.FLOAT,false,96,(i-2)*16);ext.vertexAttribDivisorANGLE(i,1);}ext.drawArraysInstancedANGLE(gl.TRIANGLES,0,batch.vertices,n);}}
const state={mode:'home',time:0,distance:0,score:0,shards:0,lives:3,lane:0,x:0,jump:0,slide:0,invulnerable:0,magnet:0,speed:19,spawn:0,objects:[],particles:[],district:0,best:Math.max(0,Number(storage.get('best','0'))||0),sound:storage.get('sound','0')==='1'};
let jumpAge=0,slideAge=0,lastTime=0,lastHUD=0,toastTimer=0,shake=0,hitReason='',audio=null,helpPaused=false;
const lanes=[-3.4,0,3.4],districts=['NEON DISTRICT','ELECTRIC AVENUE','AFTERLIGHT HEIGHTS','MIDNIGHT MILE'];
function beep(freq=440,duration=.1,type='sine',volume=.035){if(!state.sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume().catch(()=>{});const osc=audio.createOscillator(),gain=audio.createGain();osc.type=type;osc.frequency.setValueAtTime(freq,audio.currentTime);osc.frequency.exponentialRampToValueAtTime(freq*.55,audio.currentTime+duration);gain.gain.setValueAtTime(volume,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);osc.connect(gain);gain.connect(audio.destination);osc.start();osc.stop(audio.currentTime+duration);}catch{}}
function updateSound(){const on=state.sound;$('sound').setAttribute('aria-pressed',String(on));$('sound').setAttribute('aria-label',on?'Turn sound off':'Turn sound on');$('sound').innerHTML=on?'<svg viewBox="0 0 24 24"><path d="m11 5-6 4H2v6h3l6 4V5Zm4 3c3 2 3 6 0 8m3-11c5 4 5 10 0 14"/></svg>':'<svg viewBox="0 0 24 24"><path d="m11 5-6 4H2v6h3l6 4V5ZM16 9l6 6m0-6-6 6"/></svg>';}
function toast(text){$('toast').textContent=text;$('toast').classList.add('visible');toastTimer=3;}
function ui(){const playing=state.mode!=='home';document.body.classList.toggle('playing',playing);$('home').hidden=playing;$('hud').hidden=!playing;$('pause-screen').hidden=state.mode!=='paused';$('over-screen').hidden=state.mode!=='over';$('home-best').textContent=String(state.best).padStart(5,'0');}
function hud(){state.score=Math.floor(state.distance)+state.shards*25;$('score').textContent=String(state.score).padStart(5,'0');$('shards').textContent=state.shards;$('distance').textContent=Math.floor(state.distance);$('speed').textContent=Math.round(state.speed/19*100);$('district').textContent=districts[state.district%4];$('progress').style.width=(state.distance%500/5)+'%';$('hearts').setAttribute('aria-label',state.lives+' lives remaining');[...$('hearts').children].forEach((el,i)=>el.classList.toggle('lost',i>=state.lives));$('effect').hidden=state.magnet<=0;if(state.magnet>0)$('effect').textContent='◆ MAGNET · '+Math.ceil(state.magnet)+'s';}
function start(){if($('play').disabled)return;Object.assign(state,{mode:'running',time:0,distance:0,score:0,shards:0,lives:3,lane:0,x:0,jump:0,slide:0,invulnerable:0,magnet:0,speed:19,spawn:1.3,objects:[],particles:[],district:0});jumpAge=0;slideAge=0;row=0;travel=0;shake=0;powerTimer=12;ui();hud();toast('Own your line. ← → dodge · ↑ swing · ↓ slide');beep(560,.2);canvas.focus({preventScroll:true});}
function pause(){if(state.mode!=='running')return;state.mode='paused';ui();$('resume').focus();}
function resume(){if(state.mode!=='paused')return;state.mode='running';lastTime=performance.now();ui();canvas.focus({preventScroll:true});}
function home(){state.mode='home';state.objects=[];state.particles=[];state.invulnerable=0;shake=0;ui();$('play').focus();}
function gameOver(){state.mode='over';hud();const record=state.score>state.best;state.best=Math.max(state.score,state.best);storage.set('best',state.best);$('result-kicker').textContent=record?'PERSONAL BEST. SKYLINE CLAIMED.':'EVERY HERO HAS ANOTHER RUN';$('final-score').textContent=state.score.toLocaleString();$('final-distance').textContent=Math.floor(state.distance)+' m';$('final-shards').textContent=state.shards;$('final-best').textContent=state.best.toLocaleString();$('crash-tip').textContent=hitReason;ui();$('again').focus();beep(140,.35,'triangle');}
function input(action){if(state.mode!=='running')return;if(action==='left'||action==='right'){state.lane=clamp(state.lane+(action==='left'?-1:1),-1,1);beep(220,.055,'sine',.014);}if(action==='up'&&state.jump===0){state.jump=.001;jumpAge=0;state.slide=0;beep(680,.18,'sine');}if(action==='down'){state.jump=0;jumpAge=0;state.slide=1;slideAge=0;beep(190,.15,'triangle',.02);}}
function spawnObject(kind,lane,z=-112){const o={kind,lane,x:lane*3.4,z,oldZ:z,t:random()*6,done:false};state.objects.push(o);return o;}
let row=0,powerTimer=12;
function spawnRow(){row++;const lane=Math.floor(random()*3)-1;const kinds=state.distance<130?['barrier','gate']:['barrier','gate','truck'];const kind=kinds[Math.floor(random()*kinds.length)];spawnObject(kind,lane);let blocked=[lane];if(state.distance>450&&random()>.62){let second=lane===1?-1:lane+1;spawnObject(kinds[Math.floor(random()*kinds.length)],second);blocked.push(second);}const safe=[-1,0,1].filter(l=>!blocked.includes(l)),coinLane=safe[Math.floor(random()*safe.length)];for(let i=0;i<5;i++)spawnObject('shard',coinLane,-113-i*3.8);if(kind==='barrier'&&random()>.45)for(let i=0;i<3;i++){const o=spawnObject('shard',lane,-110-i*2);o.high=true;}state.spawn=1.5+random()*.48;}
function burst(x,y,z,color,count=10){for(let i=0;i<count;i++)state.particles.push({x,y,z,vx:(random()-.5)*8,vy:random()*7,vz:(random()-.5)*8,life:.6+random()*.25,color});}
function damage(kind){if(state.invulnerable>0)return;state.lives--;state.invulnerable=2.3;shake=reduced?0:.4;burst(state.x,1.3,0,C.pink,18);beep(100,.22,'sawtooth',.03);hitReason=kind==='truck'?'Solid traffic blocks the whole lane. Move left or right.':kind==='gate'?'Cyan overhead gate ahead? Slide with ↓ or swipe down.':'Pink barricades are low. Swing over them with ↑ or swipe up.';toast(state.lives?hitReason:'Run complete. Your next skyline is waiting.');if(state.lives<=0)gameOver();hud();}
function update(dt){state.time+=dt;state.speed=Math.min(36,19+state.distance/180);const step=state.speed*dt;travel+=step;state.distance+=step;state.x=mix(state.x,state.lane*3.4,1-Math.exp(-15*dt));state.invulnerable=Math.max(0,state.invulnerable-dt);state.magnet=Math.max(0,state.magnet-dt);if(state.jump>0){jumpAge+=dt;state.jump=jumpAge<1.42?Math.sin(jumpAge/1.42*Math.PI)*3.9:0;}if(state.slide>0){slideAge+=dt;if(slideAge>.92)state.slide=0;}state.spawn-=dt;if(state.spawn<=0)spawnRow();powerTimer-=dt;if(powerTimer<=0){spawnObject(row%2?'magnet':'shield',Math.floor(random()*3)-1,-105);powerTimer=14;}const d=Math.floor(state.distance/500);if(d>state.district){state.district=d;toast('WELCOME TO '+districts[d%4]);beep(880,.3);}
for(const o of state.objects){o.oldZ=o.z;o.z+=step;o.t+=dt;const collectible=['shard','shield','magnet'].includes(o.kind);if(o.done)continue;if(collectible){const y=o.high?3.8:1.5;if(state.magnet>0&&o.kind==='shard'&&o.z>-17){o.x=mix(o.x,state.x,1-Math.exp(-9*dt));if(o.high)o.high=false;}if(o.z>-.95&&o.oldZ<1.2&&Math.abs(o.x-state.x)<1.05&&Math.abs(y-(state.jump+(state.slide?.65:1.5)))<1.45){o.done=true;if(o.kind==='shard'){state.shards++;beep(980+state.shards%5*90,.065,'sine',.018);burst(o.x,y,o.z,C.gold,4);}else if(o.kind==='shield'){state.lives=Math.min(3,state.lives+1);toast('SUIT REPAIRED · +1 INTEGRITY');burst(o.x,y,0,C.cyan);beep(720,.25);}else{state.magnet=8;toast('SHARD MAGNET · 8 SECONDS');beep(820,.25);}hud();}}else if(o.z>-(o.kind==='truck'?2.65:.95)&&o.oldZ<(o.kind==='truck'?2.65:1.2)&&Math.abs(o.x-state.x)<1.22){const hit=(o.kind==='truck'&&state.jump<3.3)||(o.kind==='barrier'&&state.jump<1.45)||(o.kind==='gate'&&state.slide<=0&&state.jump<3.7);if(hit){o.done=true;damage(o.kind);}}if(state.mode!=='running')break;}
state.objects=state.objects.filter(o=>o.z<12&&(!o.done||!['shard','shield','magnet'].includes(o.kind)));for(const p of state.particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.z+=p.vz*dt+step*.4;p.vy-=15*dt;}state.particles=state.particles.filter(p=>p.life>0);}
function drawObjects(){const add=(p,s,c,g=0,r)=>object('cube',p,s,c,g,0,r,true);for(const o of state.objects){const{x,z,kind}=o;if(o.done&&['shard','shield','magnet'].includes(kind))continue;if(kind==='barrier'){add([x,.58,z],[2.7,1.16,.7],C.dark);add([x,1.12,z],[2.8,.13,.8],C.pink,1);add([x,.55,z+.36],[2.65,.55,.03],C.pink,.4);for(let j=-1;j<=1;j++)add([x+j*.8,.55,z+.39],[.17,.67,.04],C.dark,0,[0,0,-.4]);}else if(kind==='gate'){for(let a of[-1,1])add([x+a*1.44,1.8,z],[.16,3.6,.45],C.dark);add([x,2.95,z],[3,1.22,.7],C.dark);add([x,2.33,z],[2.94,.11,.8],C.cyan,1);for(let j=-1;j<=1;j++)add([x+j*.72,2.9,z+.36],[.44,.12,.04],C.cyan,1);add([x,3.6,z],[3.1,.08,.5],C.cyan,.8);}else if(kind==='truck'){add([x,1.27,z],[2.6,2.54,4.5],[.21,.24,.34]);add([x,2.8,z-.7],[2.62,.55,3.1],C.dark);add([x,1.92,z+2.27],[2.12,.68,.05],[.18,.46,.57],.3);add([x,.55,z+2.3],[2.64,.23,.08],C.dark);for(let a of[-1,1]){add([x+a*.91,.98,z+2.32],[.36,.16,.07],C.gold,1);add([x+a*1.26,.4,z+1.15],[.2,.8,.85],C.black);add([x+a*1.26,.4,z-1.35],[.2,.8,.85],C.black);}add([x,3.12,z-.65],[.55,.08,.8],C.pink,.7);}else{const y=(o.high?3.8:1.5)+Math.sin(o.t*3)*.12,color=kind==='shard'?C.gold:kind==='shield'?C.cyan:C.pink,size=kind==='shard'?.32:.5;object('octa',[x,y,z],[size,size*1.35,size],color,1,0,[0,o.t*2,kind==='magnet'?Math.PI/4:0],true);if(kind!=='shard'){object('cube',[x,y,z],[.7,.7,.04],color,.7,0,[0,o.t,Math.PI/4],true);}}}
for(const p of state.particles){const s=.08*clamp(p.life*3,0,1);object('octa',[p.x,p.y,p.z],[s,s,s],p.color,1,0,[p.life,p.life*3,0],true);}}
function drawHero(menu){const time=menu?worldTime:state.time,swinging=menu||state.jump>.05,sliding=!menu&&state.slide>0,x=menu?3+Math.sin(worldTime*.5)*.55:state.x,y=menu?4.5+(reduced?0:Math.sin(worldTime*1.2)*.7):state.jump,lean=menu?-.25:clamp((state.lane*3.4-state.x)*-.07,-.23,.23),root=matrix([x,y,0],[1,1,1],[sliding?-Math.PI/2:0,0,lean]);if(sliding)root[13]=.76;
if(!menu&&state.invulnerable>0&&Math.floor(worldTime*14)%2===0)return;
const part=(type,p,s,c,g=0,r)=>object(type,p,s,c,g,0,r,true,root),limb=(a,b,w,c)=>segment(a,b,w,c,0,'sphere',root);
part('sphere',[0,1.46,0],[.44,.59,.28],C.pink);part('sphere',[0,.95,0],[.33,.3,.26],C.black);part('sphere',[0,2.17,0],[.345,.43,.32],C.pink);
// Original split visor, chest prism and silk-suit seams.
for(const sign of[-1,1]){part('cube',[sign*.17,2.24,.287],[.245,.16,.055],C.white,.65,[0,sign*.18,sign*-.27]);part('cube',[sign*.17,2.24,-.287],[.14,.05,.032],C.dark,0,[0,0,sign*.3]);part('cube',[sign*.33,1.5,.09],[.11,.68,.35],C.black,0,[0,0,sign*.14]);}
part('octa',[0,1.53,.281],[.16,.25,.035],C.dark);part('octa',[0,1.56,-.278],[.13,.22,.035],C.white,.7);part('cube',[0,1.15,-.26],[.055,.25,.025],C.white,.5);
const stride=swinging?.3:Math.sin(time*12)*.65;const leftKnee=[-.23,.56,.15+stride*.55],rightKnee=[.23,.54,-stride*.55],leftFoot=[-.23,.09,stride],rightFoot=[.23,.09,-stride];if(swinging){leftKnee[1]=.65;leftKnee[2]=.55;leftFoot[1]=.5;leftFoot[2]=1;rightFoot[2]=-.6;}
for(const [hip,knee,foot]of[[[-.21,1,0],leftKnee,leftFoot],[[.21,1,0],rightKnee,rightFoot]]){limb(hip,knee,.16,C.black);limb(knee,foot,.135,C.pink);part('sphere',[foot[0],foot[1],foot[2]+.09],[.15,.13,.23],C.pink);}
const leftElbow=swinging?[-.72,1.85,.08]:[-.52,1.35,-stride*.5],leftHand=swinging?[-.82,2.23,.08]:[-.55,1.05,-stride*.9],rightElbow=swinging?[.63,2.03,-.1]:[.53,1.35,stride*.5],rightHand=swinging?[.85,2.61,-.12]:[.57,1.06,stride*.9];for(const [shoulder,elbow,hand]of[[[-.39,1.77,0],leftElbow,leftHand],[[.39,1.77,0],rightElbow,rightHand]]){limb(shoulder,elbow,.145,C.pink);limb(elbow,hand,.12,C.black);part('sphere',hand,[.13,.15,.13],C.pink);}
if(swinging){const hand=[x+rightHand[0],y+rightHand[1],rightHand[2]],anchor=[11,23,-20];segment(hand,anchor,.022,C.white,1);segment([x-.82,y+2.23,.08],[-12,18,-28],.011,[.59,.76,.87],.6);}
// Ground contact marker remains visible while swinging.
object('sphere',[x,.04,0],[.57,.018,.39],[.035,.045,.075],0,0,[0,0,0],true);
}
function frame(now){const dt=Math.min(.1,(now-lastTime)/1000||.016);lastTime=now;worldTime+=dt;if(state.mode==='running'){let remaining=dt;while(remaining>0&&state.mode==='running'){const step=Math.min(remaining,1/60);update(step);remaining-=step;}if(toastTimer>0){toastTimer-=dt;if(toastTimer<=0)$('toast').classList.remove('visible');}shake=Math.max(0,shake-dt);if(now-lastHUD>70){hud();lastHUD=now;}}else if(state.mode==='home'&&!reduced)travel+=dt*5;
for(const b of Object.values(batches))b.dynamic=[];drawObjects();drawHero(state.mode==='home');const menu=state.mode==='home',n=shake?Math.sin(worldTime*78)*shake*.27:0,eye=menu?(innerWidth<680?[-8,7.3,17]:[-9,7.5,16]):[state.x*.22+n,5.35+state.jump*.16,innerWidth<680?14.5:10.3],target=menu?(innerWidth<680?[7,4,-16]:[0,3.8,-18]):[state.x*.16,1.5+state.jump*.12,-18];render(eye,target);requestAnimationFrame(frame);}
$('play').onclick=start;$('again').onclick=start;$('restart-paused').onclick=start;$('pause').onclick=pause;$('resume').onclick=resume;$('quit').onclick=home;$('home-button').onclick=home;$('sound').onclick=()=>{state.sound=!state.sound;storage.set('sound',state.sound?'1':'0');updateSound();beep(660,.1);};
function closeGuide(){$('guide').close();if(helpPaused){helpPaused=false;resume();}}
$('help').onclick=()=>{helpPaused=state.mode==='running';if(helpPaused)pause();$('guide').showModal();};$('close-guide').onclick=closeGuide;$('guide-done').onclick=closeGuide;$('guide').addEventListener('cancel',e=>{e.preventDefault();closeGuide();});
canvas.tabIndex=-1;
const keyMap={ArrowLeft:'left',a:'left',A:'left',ArrowRight:'right',d:'right',D:'right',ArrowUp:'up',w:'up',W:'up',' ':'up',ArrowDown:'down',s:'down',S:'down'};
document.addEventListener('keydown',e=>{if($('guide').open)return;if(e.key==='Tab'&&['paused','over'].includes(state.mode)){const panel=$(state.mode==='paused'?'pause-screen':'over-screen');const buttons=[...panel.querySelectorAll('button')];const i=buttons.indexOf(document.activeElement);e.preventDefault();buttons[(i+(e.shiftKey?-1:1)+buttons.length)%buttons.length].focus();return;}if(e.key==='m'||e.key==='M'){if(!e.repeat)$('sound').click();return;}if(['Escape','p','P'].includes(e.key)){e.preventDefault();if(e.repeat)return;if(state.mode==='running')pause();else if(state.mode==='paused')resume();return;}if(keyMap[e.key]&&state.mode==='running'){e.preventDefault();if(!e.repeat)input(keyMap[e.key]);}});
let pointer=null;canvas.addEventListener('pointerdown',e=>{if(state.mode!=='running')return;pointer={x:e.clientX,y:e.clientY,id:e.pointerId};canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointerup',e=>{if(!pointer||e.pointerId!==pointer.id)return;const dx=e.clientX-pointer.x,dy=e.clientY-pointer.y;if(Math.max(Math.abs(dx),Math.abs(dy))>24)input(Math.abs(dx)>Math.abs(dy)?dx>0?'right':'left':dy>0?'down':'up');pointer=null;});canvas.addEventListener('pointercancel',()=>pointer=null);for(const button of document.querySelectorAll('[data-action]'))button.addEventListener('pointerdown',e=>{e.preventDefault();input(button.dataset.action);});
document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});window.addEventListener('blur',()=>pause());canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();pause();fail('The graphics connection was interrupted. Reload to rebuild the city. Your saved best score is safe.');});
try{initGL();buildCity();updateSound();ui();$('play').disabled=false;$('play-label').textContent='LET’S SWING';$('ready-note').textContent='Free to play · No sign-up · All adrenaline';requestAnimationFrame(frame);}catch(e){console.error(e);fail(e.message);}
if(new URLSearchParams(location.search).has('test'))window.__silkshift={state,input,start,pause,resume,home,update,spawnObject,damage,storage,project(p){const v=viewProjection;const w=v[3]*p[0]+v[7]*p[1]+v[11]*p[2]+v[15];return[(v[0]*p[0]+v[4]*p[1]+v[8]*p[2]+v[12])/w,(v[1]*p[0]+v[5]*p[1]+v[9]*p[2]+v[13])/w];},get gl(){return gl;},get instances(){return Object.fromEntries(Object.entries(batches).map(([k,v])=>[k,v.count]));}};
})();
