import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs';
fs.mkdirSync('test-results',{recursive:true});
const results=[];const errors=[];let browser;
const base=(process.env.SITE_URL||'http://127.0.0.1:8080').replace(/\/$/,'');
async function test(name,fn){try{await fn();results.push({name,passed:true});console.log('PASS',name);}catch(e){results.push({name,passed:false,error:e.stack});console.error('FAIL',name,e);}}
try{
 browser=await chromium.launch({headless:true,args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage']});
 const context=await browser.newContext({viewport:{width:1440,height:900}});const page=await context.newPage();
 page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base+'/?test=1',{waitUntil:'networkidle'});await page.waitForFunction(()=>window.__silkshift&& !document.getElementById('play').disabled,null,{timeout:30000});
 await test('WebGL city renders with no graphics errors',async()=>{assert.equal(await page.evaluate(()=>__silkshift.gl.getError()),0);assert.ok(await page.evaluate(()=>__silkshift.instances.cube>1000));assert.equal(await page.locator('#error').isVisible(),false);});
 await page.screenshot({path:'test-results/desktop-home.png'});
 await page.screenshot({path:'test-results/desktop-home.jpg',quality:65});
 await test('Home has no horizontal overflow and primary CTA is visible',async()=>{assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.ok(await page.locator('#play').isVisible());});
 await test('Guide opens, explains all pickups, and closes',async()=>{await page.locator('#help').click();assert.ok(await page.locator('#guide').isVisible());assert.match(await page.locator('#guide').innerText(),/8 seconds/);await page.locator('#guide-done').click();assert.equal(await page.locator('#guide').isVisible(),false);});
 await test('Run starts and score advances',async()=>{await page.locator('#play').click();await page.waitForFunction(()=>__silkshift.state.distance>1);assert.equal(await page.evaluate(()=>__silkshift.state.mode),'running');assert.equal(await page.locator('#home').isVisible(),false);});
 await test('Keyboard lane changes clamp to three lanes',async()=>{await page.keyboard.press('ArrowLeft');await page.keyboard.press('ArrowLeft');assert.equal(await page.evaluate(()=>__silkshift.state.lane),-1);await page.keyboard.press('ArrowRight');await page.keyboard.press('ArrowRight');await page.keyboard.press('ArrowRight');assert.equal(await page.evaluate(()=>__silkshift.state.lane),1);await page.keyboard.press('ArrowLeft');});
 await test('Swing and slide controls work',async()=>{await page.keyboard.press('ArrowUp');await page.waitForFunction(()=>__silkshift.state.jump>1,null,{timeout:10000});await page.screenshot({path:'test-results/desktop-swing.png'});await page.keyboard.press('ArrowDown');assert.equal(await page.evaluate(()=>__silkshift.state.slide),1);assert.equal(await page.evaluate(()=>__silkshift.state.jump),0);});
 await test('Pause freezes distance and resumes by keyboard',async()=>{await page.keyboard.press('p');const distance=await page.evaluate(()=>__silkshift.state.distance);await page.waitForTimeout(200);assert.equal(await page.evaluate(()=>__silkshift.state.distance),distance);assert.ok(await page.locator('#pause-screen').isVisible());await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>__silkshift.state.mode),'running');});
 await test('Guide pauses a run and resumes on close',async()=>{await page.locator('#help').click();assert.equal(await page.evaluate(()=>__silkshift.state.mode),'paused');await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>__silkshift.state.mode),'running');});
 await test('Deterministic collision, pickup, shield and magnet behavior',async()=>{const r=await page.evaluate(()=>{const g=__silkshift,s=g.state;g.start();s.spawn=100;s.objects=[];g.spawnObject('barrier',0,-.5);g.update(.01);const damage=s.lives===2;s.objects=[];s.invulnerable=0;g.input('up');g.update(.65);g.spawnObject('barrier',0,-.5);g.update(.01);const swing=s.lives===2;s.objects=[];g.input('down');g.spawnObject('gate',0,-.5);g.update(.01);const slide=s.lives===2;s.objects=[];s.slide=0;s.jump=0;g.spawnObject('shard',0,-.5);g.update(.01);const shard=s.shards===1;s.objects=[];g.spawnObject('shield',0,-.5);g.update(.01);const shield=s.lives===3;s.objects=[];g.spawnObject('magnet',0,-.5);g.update(.01);const magnet=s.magnet===8;return{damage,swing,slide,shard,shield,magnet};});assert.deepEqual(r,{damage:true,swing:true,slide:true,shard:true,shield:true,magnet:true});});
 await test('Game over saves best and retry resets the session',async()=>{await page.evaluate(()=>{const g=__silkshift,s=g.state;s.objects=[];s.distance=777;s.shards=4;s.lives=1;s.invulnerable=0;g.damage('truck');});assert.ok(await page.locator('#over-screen').isVisible());assert.ok(await page.evaluate(()=>Number(localStorage.getItem('silkshift.best'))>=877));await page.screenshot({path:'test-results/desktop-results.png'});await page.locator('#again').click();assert.equal(await page.evaluate(()=>__silkshift.state.lives),3);assert.equal(await page.evaluate(()=>__silkshift.state.shards),0);});
 await test('Procedural run stays bounded for five simulated minutes',async()=>{const r=await page.evaluate(()=>{const g=__silkshift,s=g.state;g.start();let peak=0;for(let i=0;i<9000;i++){s.invulnerable=1;s.lives=3;g.update(1/30);peak=Math.max(peak,s.objects.length);}g.pause();return{distance:s.distance,peak,particles:s.particles.length,speed:s.speed};});assert.ok(r.distance>8000);assert.ok(r.peak<100);assert.ok(r.particles<100);assert.equal(r.speed,36);});
 await test('Saved best survives reload',async()=>{await page.reload({waitUntil:'networkidle'});assert.ok(await page.evaluate(()=>__silkshift.state.best)>=877);});
 await test('Sound toggle updates and persists',async()=>{await page.locator('#sound').click();assert.equal(await page.locator('#sound').getAttribute('aria-pressed'),'true');await page.reload({waitUntil:'networkidle'});assert.equal(await page.locator('#sound').getAttribute('aria-pressed'),'true');});
 const mobile=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true});const mp=await mobile.newPage();mp.on('pageerror',e=>errors.push(e.message));await mp.goto(base+'/?test=1',{waitUntil:'networkidle'});await mp.waitForFunction(()=>window.__silkshift&&!document.getElementById('play').disabled);
 await test('Mobile home fits viewport with visible CTA',async()=>{assert.ok(await mp.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));const b=await mp.locator('#play').boundingBox();assert.ok(b.y+b.height<844);await mp.screenshot({path:'test-results/mobile-home.png'});});
 await test('Mobile touch buttons and swipe control the hero',async()=>{await mp.locator('#play').tap();await mp.locator('[data-action="left"]').tap();assert.equal(await mp.evaluate(()=>__silkshift.state.lane),-1);await mp.locator('[data-action="up"]').tap();await mp.waitForFunction(()=>__silkshift.state.jump>0);await mp.evaluate(()=>{const c=document.getElementById('game');c.setPointerCapture=()=>{};c.dispatchEvent(new PointerEvent('pointerdown',{pointerId:1,clientX:170,clientY:350}));c.dispatchEvent(new PointerEvent('pointerup',{pointerId:1,clientX:260,clientY:350}));});assert.equal(await mp.evaluate(()=>__silkshift.state.lane),0);await mp.screenshot({path:'test-results/mobile-run.png'});});
 await test('Small screen controls remain inside viewport',async()=>{await mp.setViewportSize({width:320,height:568});await mp.evaluate(()=>__silkshift.home());const box=await mp.locator('#play').boundingBox();assert.ok(box.x>=0&&box.x+box.width<=320);assert.ok(await mp.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));});
 await test('No JavaScript runtime errors',async()=>assert.deepEqual(errors,[]));
 await context.close();await mobile.close();
}catch(e){results.push({name:'Browser setup / runtime',passed:false,error:e.stack});console.error(e);}finally{if(browser)await browser.close();fs.writeFileSync('test-results/report.json',JSON.stringify({base,results},null,2));}
if(results.some(r=>!r.passed)||!results.length)process.exitCode=1;
